"""
Un personaje dentro del sistema.
"""
type Character {
  """Identificador único del personaje"""
  id: Int!

  """Nombre completo del personaje"""
  name: String!

  """Estado actual del personaje (Alive, Dead, Unknown)"""
  status: String

  """Especie del personaje (humano, alienígena, etc.)"""
  species: String

  """Género del personaje"""
  gender: String

  """Lugar de origen del personaje"""
  origin: String

  """URL de la imagen del personaje"""
  image: String
}
"""
Filtros para personajes
"""
input CharacterFilter {
  """Filtrar por nombre (parcial)"""
  name: String

  """Filtrar por estado (ej: Alive, Dead, Unknown)"""
  status: String

  """Filtrar por especie"""
  species: String

  """Filtrar por género"""
  gender: String

  """Filtrar por origen (parcial)"""
  origin: String
}

type Query {
  """
  Obtiene una lista de personajes que cumplen con los filtros especificados.
  Si no se especifica ningún filtro, devuelve todos los personajes.
  """
  characters(filter: CharacterFilter): [Character]
}
